### ISSUE TITLE
CUDA error during the testing stage

### ISSUE THREAD

**Issue by Fengyboy** [s9xie/hed#4]
Hi there,

I modified the testing Python code provided in the package. However when I try to predict images using the pre-trained BSDS model, I got the following error:
`F0106 13:18:05.372474  6347 syncedmem.cpp:19] Check failed: error == cudaSuccess (29 vs. 0)  driver shutting down`

I have tested on two machines, one with GTX Titan X and the other with GTX 960, giving the same error. If I supply a list images, this only happens after the code finishes processing all the images. It appears to be one of the side effects of certain version of Caffe. So far I have not yet found any solutions, could you please help me with this?

Thanks in advance,
Feng

**Comment by Fengyboy** [comment]
I've figured out the problem. Basically in the `Make.config` file, the line of `# WITH_PYTHON_LAYER := 1` should be uncommented. So after recompiling the code, it works fine now.

**Comment by daiw10** [comment]
@Fengyboy  I also got "F0212 11:44:17.588241 13859 syncedmem.cpp:19] Check failed: error == cudaSuccess (29 vs. 0)  driver shutting down"
and I have uncommented the "with_python_layer"
my environment is ubuntu16.04 and cuda 8.0,GTX TITan X and I make the caffe in the project. Would you give me some advice? Many thanks :)

**Comment by appyfizzA** [comment]
@Fengyboy  I tried your solution but it didn't work. I am still getting the same error.
